# Use uma imagem base apropriada
FROM node:18

# Defina o diretório de trabalho
WORKDIR /app

# Exponha a porta em que a aplicação vai rodar
EXPOSE 3000

# Comando padrão para iniciar a aplicação (será substituído posteriormente)
CMD ["node", "app.js"]

